### ISSUE TITLE
Create and return calculated transactionsId in prepare methods

### ISSUE THREAD

**Issue by jensneuber** [trustlines-network/clientlib#113]
To introduce a new event state ( event will be sent ) we need the transactionId before transmitting sth to the server.

This could be solved as a new return value in prepare methods:

```
{
  rawTx: ...
  txId: ... // <- new
}
```

**Comment by berndbohmeier** [comment]
This can not be solved this way as the transaction id includes the signature. Only after signing we can calculate the transaction Id. 

We should discuss how we can implement it.

**Comment by berndbohmeier** [comment]
Discussed with Jens and can not be implemented in this way.
