### ISSUE TITLE
Support interest rates

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/clientlib#141]
Interest rates are soon to be implemented in the contracts and the relay server:
- https://github.com/trustlines-network/contracts/pull/128
- https://github.com/trustlines-network/relay/pull/201

The clientlib should also be modified to support interest rates.

Related user story https://github.com/trustlines-network/project/issues/253

**Comment by andfletcher** [comment]
@dakingha69 im i able to test this?

**Comment by dakingha69** [comment]
@andfletcher yes you can test it in the app. Here is the corresponding user story https://github.com/trustlines-network/project/issues/253

**Comment by andfletcher** [comment]
works
