### ISSUE TITLE
Try to use stock parity with dev account in e2e tests

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/clientlib#156]
At the moment we use a slightly patched version of parity to have a dev account ready. The issue with stock parity https://github.com/paritytech/parity-ethereum/issues/9737 should be fixed, so we should try if we can use stock parity again. This would prevent problems like https://github.com/trustlines-network/clientlib/pull/155 in the future.

**Comment by schmir** [comment]
see https://github.com/trustlines-network/contracts/issues/176 for a similar issue in the contracts repo.
