### ISSUE TITLE
Use npm lightwallet again or switch to other wallet

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/clientlib#161]
We needed to switch to our own fork of the ethereum lightwallet because the current version was broken. 
We should switch back once this is fixed. If this is not fixed in the next time, we need to consider switching to a better maintained wallet lib.

**Comment by dakingha69** [comment]
Opened an issue with more information on switching the wallet to `ethers.js` https://github.com/trustlines-network/clientlib/issues/164. I think in the mid to long run we should definitely switch but for now stick with `eth-lightwallet`.

**Comment by dakingha69** [comment]
Closed via PR #191
