### ISSUE TITLE
CircleCI job deploy-dev fails

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/clientlib#177]
Publishing the `dev` version of the clientlib to npm fails because the package is too big as it also includes the docker image. See here https://circleci.com/gh/trustlines-network/clientlib/287.

**Comment by schmir** [comment]
nice one! everywhere else we use ~/repo as working directory where the source code get's checked out. This might also have helped here.

**Comment by dakingha69** [comment]
Hmm shouldn't it already set `~/repo` as working directory for all jobs? We are including the `defaults` anchor everywhere

https://github.com/trustlines-network/clientlib/blob/4321a04017a05848e44c0f9479a0da608400f98a/.circleci/config.yml#L3-L4

https://github.com/trustlines-network/clientlib/blob/4321a04017a05848e44c0f9479a0da608400f98a/.circleci/config.yml#L169-L170

**Comment by dakingha69** [comment]
Ah yea makes sense... Will change this also then.

**Comment by schmir** [comment]
It now fails with a different error: https://circleci.com/gh/trustlines-network/clientlib/327

The checked out directory now lives in `~`, not `~/repo~`:
```
circleci@39dc4c54121f:~$ ls
CHANGELOG.md  _bundles  lib-esm       src            tslint.json
Dockerfile    bump.sh   node_modules  tdconfig.json  webpack.config.js
LICENSE       images    package.json  tests          yarn.lock
README.md     lib       repo          tsconfig.json
circleci@39dc4c54121f:~$ ls repo
```

**Comment by schmir** [comment]
There are still some calls to `persist_workspace` with root `~/repo` and `attach_workspace: at: ~/repo` calls left in the file.
We should probably use `~` as root and also attach to `~` everywhere.

**Comment by dakingha69** [comment]
Ok will fix this.
