### ISSUE TITLE
Create meta transaction signer

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/clientlib#194]
We need to create a meta transaction signer that uses the information like next nonce from identity contracts and will create a signed meta transaction. 

Belongs to https://github.com/trustlines-network/project/issues/272

**Comment by cducrest** [comment]
This will rely on e2e tests to verify that the interaction with the identity contract works, the ability to deploy an identity contract has to be implemented first: https://github.com/trustlines-network/clientlib/issues/196
