### ISSUE TITLE
What is createOnboardingMsg supposed to do

### ISSUE THREAD

**Issue by cducrest** [trustlines-network/clientlib#207]
When adding the identity wallet, we ended up modifying createOnboardingMsg() :
https://github.com/trustlines-network/clientlib/blob/develop/src/User.ts#L153.
We changed its input from `ethersKeystore` to `serializedWallet` but were unsure of what the function is used for and if it needs to be modified / deleted.

My understandingis that it is used to create a message to ask for ETH to another user. It takes as input the ethersKeystore to be able to recover the address that should receive the eth. This is not necessary as it could use `this.address`.

**Comment by dakingha69** [comment]
Yes exactly your understanding of this method is correct. It was designed this way because it was an old requirement still from the mobileapp... But as we changed the onboarding flow in the mobileapp since then, it should be no problem to use `this.address` instead.
