### ISSUE TITLE
Escaping in buildUrl, createLink

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/clientlib#38]
We need to improve the encoding of parameters into the url and prevent problems when special characters like ? and & are included in the parameters. 

See
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/encodeURI
and
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

**Comment by berndbohmeier** [comment]
Btw what is the difference between buildUrl, createLink, why dont we have just one function?

**Comment by dakingha69** [comment]
the difference is that `buildUrl` is used for building urls that are sent to the relay server whereas `createLink` is used for building links that are sent to other users such as a link to a contact. but yea theoretically just one function can be used.

**Comment by dakingha69** [comment]
done
