### ISSUE TITLE
Function to withdraw wrapped ETH from a wrapped Ether ERC20 token contract 

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/clientlib#54]
To be able to trade ETH <-> TL money, the user needs to be able to unwrap his wrapped ETH. This is an on-chain tx. See https://github.com/0xProject/0x-monorepo/blob/6ba6bec1054ee89edc48d2128940c84c727a4b1d/packages/0x.js/src/contract_wrappers/ether_token_wrapper.ts#L71

**Comment by berndbohmeier** [comment]
Note, we use a self unwrapping ether token. (To try it out) This means on a transfer, Wrapped ETH gets automatically unwrapped.
